### PR TITLE
Code Review Request

### PR DESCRIPTION
**Pull request by ayush0711**
Hi, @amansingh220 

I have added the deal module's code except deal controller.

Have a look on that and merge my code.

### CODE REVIEW

**Review by amansingh220 — COMMENTED** [review]
Hello, @ayush0711

Please Update your code there are some conflicts in your code.

Good luck.

**Review by amansingh220 — CHANGES_REQUESTED** [review]
Hi, @ayush0711 

Change The files and push again right now.

**Comment by ayush0711** [comment]
Hello, @amansingh220 

Doing that.

**Comment by ayush0711** [comment]
hello, @amansingh220 

I have done the requested changes 

Thanks

**Comment by ayush0711** [comment]
hello, @amansingh220

I have done the requested changes

Thanks

**Review by amansingh220 — APPROVED** [review]
Hi, @ayush0711 

Fine It's looking go ahead.

Regards

@amansingh220

**Comment by amansingh220** [comment]
Hi, @ayush0711 

There are some Conflicts wait till next notice.

Regards
@ayush0711

**Pull request closed without merging**
